config/routes.rb
Rails.application.routes.draw do
  # resources :reponses

  # resources :annonces

  resources :residences

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks'
  }, path: 'users', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  resources :annonces do
    resources :reponses do
    end
  end

  # static pages and links
  root 'main#index'
  get '/termes', to: 'main#termes'
  get '/politique', to: 'main#politique'
  get '/contact', to: 'main#contact'

  get 'users/:id/annonces' => 'annonces#index', :as => :user_annonces
  get '/users/:id',   to: 'users#show', :as => :user_profil

  # error pages
  %w( 404 422 500 503 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  #If no route matches
  get ":url" => "application#redirect_user", :constraints => { :url => /.*/ }
end

app/views/shared/_footer.html.erb
  </div>
  <hr>
  <footer>
  <div id="sub-footer">

    <div class="container">
        <div class="col-lg-8">
          <div class="copyright">
            <p>
              <span>&copy; Colleg Coloc 2015 collegcoloc@gmail.com 95 39 18 06.</span>
              <span><%= link_to("Politique d'utilisation", '/politique') %> </span>
              <span><%= link_to('Termes du service', '/termes') %></span>
              <span><%= link_to('Nous contacter', '/contact') %></span>
            </p>
          </div>
        </div>

        <div class="col-lg-4">
          <ul class="social-network">
            <li><a href="#" data-placement="top" title="Facebook"><i class="fa fa-facebook"></i></a></li>
            <li><a href="#" data-placement="top" title="Twitter"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#" data-placement="top" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
            <li><a href="#" data-placement="top" title="Pinterest"><i class="fa fa-pinterest"></i></a></li>
            <li><a href="#" data-placement="top" title="Google plus"><i class="fa fa-google-plus"></i></a></li>
          </ul>
        </div>
      </div>

  </div>
  <a href="#" class="scrollup"><i class="fa fa-angle-up active"></i></a>
  </footer>
</div>

app/views/shared/_header.html.erb
<div class="container">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <a class="navbar-brand" href="http://www.emploisite.com">Emploi site</a>

      </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
            <li><%= link_to('Toutes les annonces', annonces_path()) %></li>
          <% if user_signed_in? %>
            <li>
            <%= link_to('Mes annonces et réponses', user_annonces_path(current_user)) %>
            </li>
            <li class="dropdown">
              <a href="#" id="dLabel" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <% if (current_user.prenom && current_user.nom) %>
                    <%= current_user.prenom + '  ' + current_user.nom %>
                <% else %>
                    <%= current_user.email %>
                <% end %>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                <li>
                <%= link_to('Se déconnecter', destroy_user_session_path, :method => :delete) %>
                </li>
                <li>
                <%= link_to('Modifier son profil', edit_user_registration_path) %>
                </li>
              </ul>
            </li>
          <% else %>
            <li>
            <%= link_to('Login', new_user_session_path)  %>
            </li>
            <li>
            <%= link_to('Register', new_user_registration_path)  %>
            </li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <div>
    <!-- need by devise -->
    <!--% if notice %>
      <p class="alert alert-info"><%= notice %></p>
    <!-- % end %-->

    <% if alert %>
      <p class="alert alert-warning"><%= alert %></p>
    <% end %>

  </div>
</div>
<div class="container">