config/routes.rb
Rails.application.routes.draw do
  # resources :reponses

  # resources :annonces

  resources :residences

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks'
  }, path: 'users', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  resources :annonces do
    resources :reponses do
    end
  end

  # static pages and links
  root 'main#index'
  get '/termes', to: 'main#termes'
  get '/politique', to: 'main#politique'
  get '/contact', to: 'main#contact'

  get 'users/:id/annonces' => 'annonces#index', :as => :user_annonces
  get '/users/:id',   to: 'users#show', :as => :user_profil

  # error pages
  %w( 404 422 500 503 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  #If no route matches
  get ":url" => "application#redirect_user", :constraints => { :url => /.*/ }
end

app/controllers/reponses_controller.rb
class ReponsesController < ApplicationController
  before_action :set_reponse, only: [:show, :edit, :update, :destroy]
  before_action :set_annonce, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:index, :create, :new, :show, :edit, :update, :destroy]

  # GET /reponses
  # GET /reponses.json
  def index
    @reponses = Reponse.all
  end

  # GET /reponses/1
  # GET /reponses/1.json
  def show
  end

  # GET /reponses/new
  def new
    @reponse = Reponse.new
  end

  # GET /reponses/1/edit
  def edit
  end

  # POST /reponses
  # POST /reponses.json
  def create
    @reponse = Reponse.new(reponse_params)

    respond_to do |format|
      if @reponse.save
        format.html { redirect_to annonce_reponse_url(@annonce, @reponse), notice: 'Reponse envoyé.' }
        format.json { render :show, status: :created, location: @reponse }
      else
        format.html { render :new }
        format.json { render json: @reponse.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reponses/1
  # PATCH/PUT /reponses/1.json
  def update
    respond_to do |format|
      if @reponse.update(reponse_params)
        format.html { redirect_to annonce_reponse_url(@annonce, @reponse), notice: 'Reponse mise à jour.' }
        format.json { render :show, status: :ok, location: @reponse }
      else
        format.html { render :edit }
        format.json { render json: @reponse.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reponses/1
  # DELETE /reponses/1.json
  def destroy
    @reponse.destroy
    respond_to do |format|
      format.html { redirect_to reponses_url, notice: 'Reponse supprimée.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reponse
      @reponse = Reponse.find(params[:id])
    end

    def set_annonce
      @annonce = Annonce.find(params[:annonce_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reponse_params
      params.require(:reponse).permit(:Contenu)
    end
end

app/helpers/reponses_helper.rb
module ReponsesHelper
end

app/views/reponses/_form.html.erb
<%= form_for([@annonce, @reponse]) do |f| %>
  <% if @reponse.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reponse.errors.count, "error") %> prohibited this reponse from being saved:</h2>

      <ul>
      <% @reponse.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Contenu %><br>
    <%= f.text_area :Contenu %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reponses/edit.html.erb
<h1>Editing Reponse</h1>

<%= render 'form' %>

<%= link_to 'Voir', @reponse %> |
<%= link_to 'Retour', reponses_path %>

app/views/reponses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reponses</h1>
<div class="row pads">
<table class="table">
  <thead>
    <tr>
<%= link_to 'Nouvelle réponse', new_annonce_reponse_path %>
      <th>Reponses</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reponses.each do |reponse| %>
      <tr>
        <td><%= reponse.Contenu %></td>
        <td style="width: 100px;"><button class="btn btn-success btn-sm"><%= link_to 'Voir', annonce_reponse_path(@annonce, reponse), class: "colore" %></button></td>
        <td style="width: 100px;"><button class="btn btn-warning btn-sm"><%= link_to 'Modifier', edit_annonce_reponse_path(@annonce, reponse), class: "colore" %></td>
        <td style="width: 100px;"><button class="btn btn-danger btn-sm"><%= link_to 'Supprimer', annonce_reponse_path(@annonce, reponse), method: :delete, data: { confirm: 'Etes-vous sûre de vouloir Supprimer?' }, class: "colore" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

app/views/reponses/new.html.erb
<%= render "shared/header" %>

<h1>New Reponse</h1>


<p id="notice"><%= notice %></p>

<p>
  <strong>Titre:</strong>
  <%= @annonce.Titre %>
</p>

<p>
  <strong>Description:</strong>
  <%= @annonce.Description %>
</p>

<p>
  <strong>Apercu:</strong>
  <%= @annonce.Apercu %>
</p>

<p>
  <strong>Type:</strong>
  <%= @annonce.Type %>
</p>

<p>
  <strong>Adresse:</strong>
  <%= @annonce.Adresse %>
</p>

<p>
  <strong>Datecloture:</strong>
  <%= @annonce.DateCloture %>
</p>

<hr>
<p>
  <strong>En réponse, j'écris:</strong>
</p>

<%= render 'form' %>

<%= link_to 'Retour', annonce_reponses_path %>

<%= render "shared/footer" %>

app/views/reponses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Contenu:</strong>
  <%= @reponse.Contenu %>
</p>
<%= link_to 'Modifier', edit_annonce_reponse_path(@annonce, @reponse) %> |
<%= link_to 'Retour', annonce_reponses_path %>