config/routes.rb
Rails.application.routes.draw do
  # resources :reponses

  # resources :annonces

  resources :residences

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks'
  }, path: 'users', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  resources :annonces do
    resources :reponses do
    end
  end

  # static pages and links
  root 'main#index'
  get '/termes', to: 'main#termes'
  get '/politique', to: 'main#politique'
  get '/contact', to: 'main#contact'

  get 'users/:id/annonces' => 'annonces#index', :as => :user_annonces
  get '/users/:id',   to: 'users#show', :as => :user_profil

  # error pages
  %w( 404 422 500 503 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  #If no route matches
  get ":url" => "application#redirect_user", :constraints => { :url => /.*/ }
end

app/models/annonce.rb
class Annonce < ActiveRecord::Base
  belongs_to :user
  has_many :reponses

  has_attached_file :Apercu, default_url: "1.jpg"
  validates_attachment :Apercu, :styles => { :medium => "300x300>", :thumb => "100x100>" },
   :content_type => { :content_type => ["image/jpeg", "image/gif", "image/png"]  },
   :path => "/public/:annonces/:basename.:extension",
   :url => "/:annonces/:basename.:extension",
   :default_url => 'public/annonces/1.png'

  # validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  validates :Titre, :Description, :Type, :Budget, :Adresse, :DateCloture, :user_id, presence: true
  validates :Budget, :numericality => {:only_integer => true}

  acts_as_commentable :public, :private, { class_name: 'Reponse' }
end

app/controllers/annonces_controller.rb
class AnnoncesController < ApplicationController
  before_action :set_annonce, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:create, :new, :edit, :update, :destroy]

  # GET /annonces
  # GET /annonces.json
  def index
    p params
    if params[:id]
      @annonces = Annonce.where(user_id: params[:id]).includes(:reponses)
    else
      @annonces = Annonce.all
    end
  end

  # GET /annonces/1
  # GET /annonces/1.json
  def show
    # @annonce = @annonce.includes(:reponses)
  end

  # GET /annonces/new
  def new
    @annonce = Annonce.new
  end

  # GET /annonces/1/edit
  def edit
  end

  # POST /annonces
  # POST /annonces.json
  def create
    @annonce = Annonce.new(annonce_params)
    @annonce.user_id = current_user.id

    respond_to do |format|
      if @annonce.save
        format.html { redirect_to @annonce, notice: 'Annonce enregistrée et publiée.' }
        format.json { render :show, status: :created, location: @annonce }
      else
        format.html { render :new }
        format.json { render json: @annonce.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /annonces/1
  # PATCH/PUT /annonces/1.json
  def update
    respond_to do |format|
      if @annonce.update(annonce_params)
        format.html { redirect_to @annonce, notice: 'Annonce mise à jour.' }
        format.json { render :show, status: :ok, location: @annonce }
      else
        format.html { render :edit }
        format.json { render json: @annonce.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /annonces/1
  # DELETE /annonces/1.json
  def destroy
    @annonce.destroy
    respond_to do |format|
      format.html { redirect_to annonces_url, notice: 'Annonce supprimée.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_annonce
      @annonce = Annonce.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def annonce_params
      params.require(:annonce).permit(:Titre, :Description, :Apercu, :Type, :Budget, :Adresse, :DateCloture)
    end
end

app/helpers/annonces_helper.rb
module AnnoncesHelper
end

app/views/annonces/_form.html.erb
<div class="row">
  <div class="col-md-5 col-md-offset-4">
    <div class="panel panel-default user-panel pad">

      <%= form_for(@annonce) do |f| %>
        <% if @annonce.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@annonce.errors.count, "error") %> prohibited this annonce from being saved:</h2>

            <ul>
            <% @annonce.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

          <%= f.label :Titre %><br>
          <%= f.text_field :Titre, :required => true, class: "form-control" %>

          <%= f.label :Description %><br>
          <%= f.text_area :Description, :required => true, class: "form-control" %>


          <%= f.label :Apercu %><br>
          <%= f.file_field :Apercu, :required => true, class: "form-control" %>


          <%= f.label :Type %><br>
          <%= f.select(:Type, ['Colocation', 'Location'], :class => 'my_style_class')%>

          <%= f.label :Budget %><br>
          <%= f.number_field :Budget, class: "form-control" %> <span> F CFA </span>


          <%= f.label :Adresse %><br>
          <%= f.text_field :Adresse, :required => true, class: "form-control" %>


          <%= f.label :DateCloture %><br>
          <%= f.date_select :DateCloture, class: "form-control" %><br><br>


          <%= f.submit "Create Add", class: "btn btn-primary btn-block" %>
      <% end %>
    </div>
  </div>
</div>

app/views/annonces/edit.html.erb
<%= render "shared/header" %>

<h1>Editing Annonce</h1>

<%= render 'form' %>

<%= link_to 'Voir', @annonce %> |
<%= link_to 'Retour', annonces_path %>

<%= render "shared/footer" %>

app/views/annonces/index.html.erb
<%= render "shared/header" %>

<p id="notice"><%= notice %></p>

<h1>Listing Annonces</h1>

<table>
  <thead>
    <tr>
      <th>Titre</th>
      <th>Description</th>
      <th>Apercu</th>
      <th>Type</th>
      <th>Adresse</th>
      <th>Datecloture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @annonces.each do |annonce| %>
      <tr>
        <td><%= annonce.Titre %></td>
        <td><%= annonce.Description %></td>
        <td><%= annonce.Type %></td>
        <td><%= annonce.Adresse %></td>
        <td><%= annonce.DateCloture %></td>
        <td><%= link_to 'Voir', annonce %></td>
        <% if (current_user.id == annonce.user_id) %>
          <td><%= link_to 'Voir les réponses', annonce_reponses_path(annonce) %></td>
          <td><%= link_to 'Modifier', edit_annonce_path(annonce) %></td>
          <td><%= link_to 'Supprimer', annonce, method: :delete, data: { confirm: 'En êtes-vous sûr?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nouvelle annonce', new_annonce_path %>

<%= render "shared/footer" %>

app/views/annonces/new.html.erb
<%= render "shared/header" %>
<center><h3>New Annonce</h3></center>

<%= render 'form' %>

<%= link_to 'Retour', annonces_path %>
<%= render "shared/footer" %>

app/views/annonces/show.html.erb
<%= render "shared/header" %>

<p id="notice"><%= notice %></p>

<div class="annonce">

  <%= image_tag @annonce.Apercu.url %>

<p>
  <strong>Titre:</strong>
  <%= @annonce.Titre %>
</p>

<p>
  <strong>Description:</strong>
  <%= @annonce.Description %>
</p>

<p>
  <strong>Type:</strong>
  <%= @annonce.Type %>
</p>

<p>
  <strong>Adresse:</strong>
  <%= @annonce.Adresse %>
</p>

<p>
  <strong>Date clôture de proposition:</strong>
  <%= @annonce.DateCloture %>
</p>

</div>

<% @annonce.reponses.each do |reponse|%>
  <p>
    <strong>Contenu:</strong>
    <%= reponse.Contenu %>
  </p>
<% end %>

<%= link_to 'Nouvelle reponse', new_annonce_reponse_path(@annonce) %> |
<% if (current_user.id == @annonce.user_id) %>
  <%= link_to 'Voir les réponses', annonce_reponses_path(@annonce) %> |
  <%= link_to 'Modifier', edit_annonce_path(@annonce) %> |
<% end %>
<%= link_to 'Retour', annonces_path %>

<%= render "shared/footer" %>