config/routes.rb
Rails.application.routes.draw do
  # resources :reponses

  # resources :annonces

  resources :residences

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks'
  }, path: 'users', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  resources :annonces do
    resources :reponses do
    end
  end

  # static pages and links
  root 'main#index'
  get '/termes', to: 'main#termes'
  get '/politique', to: 'main#politique'
  get '/contact', to: 'main#contact'

  get 'users/:id/annonces' => 'annonces#index', :as => :user_annonces
  get '/users/:id',   to: 'users#show', :as => :user_profil

  # error pages
  %w( 404 422 500 503 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  #If no route matches
  get ":url" => "application#redirect_user", :constraints => { :url => /.*/ }
end

app/models/residence.rb
class Residence < ActiveRecord::Base
  has_attached_file :Apercu, default_url: "2.jpg"
  validates_attachment :Apercu, :styles => { :medium => "100x100>", :thumb => "64x64>" },
   :content_type => { :content_type => ["image/jpeg", "image/gif", "image/png"] },
   :path => ":rails_root/public/residences/:id/:basename.:extension",
   :url => ":rails_root/public/residences/:id/:basename.:extension"

  # validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  validates :Titre, :Description, presence: true
end

app/controllers/residences_controller.rb
class ResidencesController < ApplicationController
  before_action :set_residence, only: [:show, :edit, :update, :destroy]

  # GET /residences
  # GET /residences.json
  def index
    @residences = Residence.all
  end

  # GET /residences/1
  # GET /residences/1.json
  def show
  end

  # GET /residences/new
  def new
    @residence = Residence.new
  end

  # GET /residences/1/edit
  def edit
  end

  # POST /residences
  # POST /residences.json
  def create
    @residence = Residence.new(residence_params)

    respond_to do |format|
      if @residence.save
        format.html { redirect_to @residence, notice: 'Residence was successfully created.' }
        format.json { render :show, status: :created, location: @residence }
      else
        format.html { render :new }
        format.json { render json: @residence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /residences/1
  # PATCH/PUT /residences/1.json
  def update
    respond_to do |format|
      if @residence.update(residence_params)
        format.html { redirect_to @residence, notice: 'Residence was successfully updated.' }
        format.json { render :show, status: :ok, location: @residence }
      else
        format.html { render :edit }
        format.json { render json: @residence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /residences/1
  # DELETE /residences/1.json
  def destroy
    @residence.destroy
    respond_to do |format|
      format.html { redirect_to residences_url, notice: 'Residence was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_residence
      @residence = Residence.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def residence_params
      params.require(:residence).permit(:Titre, :Description, :Apercu)
    end
end

app/helpers/residences_helper.rb
module ResidencesHelper
end

app/views/residences/_form.html.erb
<%= form_for(@residence) do |f| %>
  <% if @residence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@residence.errors.count, "error") %> prohibited this residence from being saved:</h2>

      <ul>
      <% @residence.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Titre %><br>
    <%= f.text_field :Titre %>
  </div>
  <div class="field">
    <%= f.label :Description %><br>
    <%= f.text_area :Description %>
  </div>
  <div class="field">
    <%= f.label :Apercu %><br>
    <%= f.text_field :Apercu %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/residences/edit.html.erb
<h1>Editing Residence</h1>

<%= render 'form' %>

<%= link_to 'Show', @residence %> |
<%= link_to 'Back', residences_path %>

app/views/residences/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Residences</h1>

<table>
  <thead>
    <tr>
      <th>Titre</th>
      <th>Description</th>
      <th>Apercu</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @residences.each do |residence| %>
      <tr>
        <td><%= image_tag residence.Apercu.url %></td>
        <td><%= residence.Titre %></td>
        <td><%= residence.Description %></td>
        <td><%= link_to 'Show', residence %></td>
        <td><%= link_to 'Edit', edit_residence_path(residence) %></td>
        <td><%= link_to 'Destroy', residence, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Residence', new_residence_path %>

app/views/residences/new.html.erb
<h1>New Residence</h1>

<%= render 'form' %>

<%= link_to 'Back', residences_path %>

app/views/residences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titre:</strong>
  <%= @residence.Titre %>
</p>

<p>
  <strong>Description:</strong>
  <%= @residence.Description %>
</p>

<p>
  <strong>Apercu:</strong>
  <%= @residence.Apercu %>
</p>

<%= link_to 'Modifier', edit_residence_path(@residence) %> |
<%= link_to 'Retour', residences_path %>